"""Create missions and routes

Revision ID: bd32803e677f
Revises: 
Create Date: 2026-10-09 14:00:45.328695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd32803e677f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('planning_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_missions_name_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('drone_index', sa.Integer(), nullable=False),
    sa.Column('goal_index', sa.Integer(), nullable=False),
    sa.Column('route_coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.CheckConstraint("distance >= 0 AND distance < 'Infinity'::double precision", name='ck_routes_distance_valid'),
    sa.CheckConstraint("jsonb_typeof(route_coordinates) = 'array' AND jsonb_array_length(route_coordinates) > 0", name='ck_routes_coordinates_nonempty'),
    sa.CheckConstraint('drone_index >= 0', name='ck_routes_drone_index_nonnegative'),
    sa.CheckConstraint('goal_index >= 0', name='ck_routes_goal_index_nonnegative'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'drone_index', name='uq_routes_mission_drone'),
    sa.UniqueConstraint('mission_id', 'goal_index', name='uq_routes_mission_goal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    op.drop_table('missions')
    # ### end Alembic commands ###
