"""Add organization users

Revision ID: d8b033fc3257
Revises: c454b4fd9450
Create Date: 2026-10-10 12:11:51.075716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b033fc3257'
down_revision: Union[str, Sequence[str], None] = 'c454b4fd9450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'viewer'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'operator', 'viewer')", name='ck_users_role_valid'),
    sa.CheckConstraint('length(trim(email)) > 0 AND email = lower(trim(email))', name='ck_users_email_normalized'),
    sa.CheckConstraint('length(trim(password_hash)) > 0', name='ck_users_password_hash_not_blank'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_users_organization_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
